name: Build subway_tool

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'build.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Build
        env:
          NDK_CC: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
        run: |
          mkdir -p build
          chmod +x build.sh
          bash build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: panxcz-subway
          path: |
            build/subway_tool
            build/liboverlay.so
          retention-days: 90
